In [3]:
import pandas as pd

In [4]:
# Data read form csv
df = pd.read_csv("weather_data.csv")
df

          day  temperature  windspeed  event
0    1/1/2022           30          5  sunny
1    2/1/2022           24          5   rain
2    3/1/2022           25          8  sunny
3    4/1/2022           26          8   rain
4    5/1/2022           27          8  sunny
5    6/1/2022           25          5   rain
6    7/1/2022           31          9   rain
7    8/1/2022           25          9  sunny
8    9/1/2022           26          5   rain
9   10/1/2022           28          5   snow
10  11/1/2022           29          7   snow
11  12/1/2022           32          7   snow
12  13/1/2022           24          7   rain
13  14/1/2022           28          5   rain
14  15/1/2022           27          6   rain

In [11]:
# Data read form excel
df_ex = pd.read_excel("weather_dataset.xlsx", "Sheet1") #excel dependent on openpyxl (pip install openpyxl)
df_ex

          day  temperature  windspeed  event
0  2022-01-01           30          5  sunny
1  2022-01-02           24          5   rain
2  2022-01-03           25          8  sunny
3  2022-01-04           26          8   rain
4  2022-01-05           27          8  sunny
5  2022-01-06           25          5   rain
6  2022-01-07           31          9   rain
7  2022-01-08           25          9  sunny
8  2022-01-09           26          5   rain
9  2022-01-10           28          5   snow
10 2022-01-11           29          7   snow
11 2022-01-12           32          7   snow
12 2022-01-13           24          7   rain
13 2022-01-14           28          5   rain
14 2022-01-15           27          6   rain

In [19]:
df = pd.read_csv("weather_data.csv").to_dict() #csv to python dictionary
# df

('day', 'temperature', 'windspeed', 'event')

In [17]:
weather_data = {
    'day': {
        0: '1/1/2022',
        1: '2/1/2022',
        2: '3/1/2022',
        3: '4/1/2022',
        4: '5/1/2022',
        5: '6/1/2022',
        6: '7/1/2022',
        7: '8/1/2022',
        8: '9/1/2022',
        9: '10/1/2022',
        10: '11/1/2022',
        11: '12/1/2022',
        12: '13/1/2022',
        13: '14/1/2022',
        14: '15/1/2022'
    },
    'temperature': {
        0: 30,
        1: 24,
        2: 25,
        3: 26,
        4: 27,
        5: 25,
        6: 31,
        7: 25,
        8: 26,
        9: 28,
        10: 29,
        11: 32,
        12: 24,
        13: 28,
        14: 27
    },
    'windspeed': {
        0: 5,
        1: 5,
        2: 8,
        3: 8,
        4: 8,
        5: 5,
        6: 9,
        7: 9,
        8: 5,
        9: 5,
        10: 7,
        11: 7,
        12: 7,
        13: 5,
        14: 6
    },
    'event': {
        0: 'sunny',
        1: 'rain',
        2: 'sunny',
        3: 'rain',
        4: 'sunny',
        5: 'rain',
        6: 'rain',
        7: 'sunny',
        8: 'rain',
        9: 'snow',
        10: 'snow',
        11: 'snow',
        12: 'rain',
        13: 'rain',
        14: 'rain'
    }
}


# Dataframe create form python dictionary
df = pd.DataFrame(weather_data)
df

          day  temperature  windspeed  event
0    1/1/2022           30          5  sunny
1    2/1/2022           24          5   rain
2    3/1/2022           25          8  sunny
3    4/1/2022           26          8   rain
4    5/1/2022           27          8  sunny
5    6/1/2022           25          5   rain
6    7/1/2022           31          9   rain
7    8/1/2022           25          9  sunny
8    9/1/2022           26          5   rain
9   10/1/2022           28          5   snow
10  11/1/2022           29          7   snow
11  12/1/2022           32          7   snow
12  13/1/2022           24          7   rain
13  14/1/2022           28          5   rain
14  15/1/2022           27          6   rain